[[redirects]]
  from = "https://hcbuffs.netlify.app/*"
  to = "https://hcbuffs.com/:splat"
  status = 301
  force = true

[build]
  functions = "netlify/functions"
  node_bundler = "esbuild"
  publish = "."

[build.environment]
  NODE_VERSION = "16"

[functions]
  node_bundler = "esbuild"

[functions.cleanup-buffs]
  schedule = "0 0 * * *" 

# Cache static assets aggressively
[[headers]]
  for = "/*.{css,js}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Timing-Allow-Origin = "*"

[[headers]]
  for = "/*.{png,jpg,jpeg,webp,svg,ico}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.{json}"
  [headers.values]
    Cache-Control = "public, max-age=60, stale-while-revalidate=600"

[[headers]]
  for = "/10minalert.mp3"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 
