[[redirects]]
  from = "https://hcbuffs.netlify.app/*"
  to = "https://hcbuffs.com/:splat"
  status = 301
  force = true

[build]
  functions = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "16"
