[[redirects]]
  from = "https://hcbuffs.netlify.app/*"
  to = "https://hcbuffs.com/:splat"
  status = 301
  force = true

[build]
  functions = "netlify/functions"
  node_bundler = "esbuild"
  publish = "."

[build.environment]
  NODE_VERSION = "16"

[functions]
  node_bundler = "esbuild"

[functions.cleanup-buffs]
  schedule = "0 0 * * *" 
