let buffs=[],faction="horde";async function loadBuffs(){try{let e=`${faction}_buffs.json`,t=await fetch(e);if(!t.ok)throw Error(`HTTP error! Status: ${t.status}`);let n=await t.json();(buffs=Array.from(new Map(n.map(e=>[e.datetime+e.guild,e])).values())).sort((e,t)=>new Date(e.datetime)-new Date(t.datetime)),displayBuffs(),startCountdown()}catch(i){document.getElementById("buffList").innerHTML=`<tr><td colspan="5">Error loading buffs: ${i.message}</td></tr>`,buffs=[]}}function updateFaction(){faction=document.getElementById("faction").value,document.getElementById("buffList").innerHTML="",document.getElementById("countdownTimer").textContent="--:--:--","alliance"===faction?document.body.classList.add("alliance"):document.body.classList.remove("alliance"),loadBuffs(),localStorage.removeItem("alertedBuffs")}function formatDateTime(e,t=!1){return t?e.toLocaleString("en-US",{timeZone:"America/Denver",weekday:"long",month:"long",day:"numeric",hour:"numeric",minute:"numeric",hour12:!0}):e.toLocaleString("en-US",{timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone,weekday:"long",hour:"numeric",minute:"numeric",hour12:!0})}function displayBuffs(){let e=document.getElementById("buffList");if(e.innerHTML="",0===buffs.length){e.innerHTML='<tr><td colspan="5">No buffs available.</td></tr>';return}let t=Intl.DateTimeFormat().resolvedOptions().timeZone,n=new Date,i=new Date(n.toLocaleString("en-US",{timeZone:t})),o=buffs.filter(e=>{let n=new Date(e.datetime),o=new Date(n.toLocaleString("en-US",{timeZone:t}));return o>i});if(0===o.length){e.innerHTML='<tr><td colspan="5">No upcoming buffs available.</td></tr>';return}o.forEach(t=>{let n=new Date(t.datetime);isNaN(n.getTime())&&(n=new Date);let i=formatDateTime(n,!0),o=formatDateTime(n,!1),a=document.createElement("tr");a.innerHTML=`
    <td>${i}</td>
    <td>${o}</td>
    <td>${t.guild}</td>
    <td>Onyxia</td>
    <td>${t.notes||""}</td>
`,e.appendChild(a)})}function searchBuffs(){let e=document.getElementById("buffSearch").value.toLowerCase(),t=document.getElementById("buffList");if(t.innerHTML="",0===buffs.length){t.innerHTML='<tr><td colspan="5">No buffs available.</td></tr>';return}let n=Intl.DateTimeFormat().resolvedOptions().timeZone,i=new Date,o=new Date(i.toLocaleString("en-US",{timeZone:n})),a=buffs.filter(t=>{let n=formatDateTime(new Date(t.datetime),!0).toLowerCase(),i=t.guild.toLowerCase(),o=(t.notes||"").toLowerCase();return n.includes(e)||i.includes(e)||o.includes(e)}),r=a.filter(e=>{let t=new Date(e.datetime),i=new Date(t.toLocaleString("en-US",{timeZone:n}));return i>o});if(0===r.length){t.innerHTML='<tr><td colspan="5">No matching buffs available.</td></tr>';return}r.forEach(e=>{let n=new Date(e.datetime),i=formatDateTime(n,!0),o=formatDateTime(n,!1),a=document.createElement("tr");a.innerHTML=`
    <td>${i}</td>
    <td>${o}</td>
    <td>${e.guild}</td>
    <td>Onyxia</td>
    <td>${e.notes||""}</td>
`,t.appendChild(a)})}function startCountdown(){let e=null;function t(){if(0===buffs.length){document.getElementById("countdownTimer").textContent="No upcoming buffs";return}let t=new Date,n=Intl.DateTimeFormat().resolvedOptions().timeZone,i=new Date(t.toLocaleString("en-US",{timeZone:n})),o=buffs.find(e=>{let t=new Date(e.datetime),o=new Date(t.toLocaleString("en-US",{timeZone:n}));return o>i});if(!o){document.getElementById("countdownTimer").textContent="No upcoming buffs",null!==e&&(displayBuffs(),e=null);return}let a=new Date(o.datetime),r=new Date(a.toLocaleString("en-US",{timeZone:n})),f=r-i,l=new Set(JSON.parse(localStorage.getItem("alertedBuffs"))||[]),d=`${o.datetime}_${o.guild}`;if(f<=6e5&&f>0&&!l.has(d)&&(function e(t){let n=new Audio("/10minalert.mp3");n.play().catch(e=>console.warn("Sound playback failed:",e)),"Notification"in window?("granted"!==Notification.permission&&"denied"!==Notification.permission&&Notification.requestPermission(),"granted"===Notification.permission?new Notification("Buff Alert!",{body:`Onyxia buff from ${t.guild} drops in 10 minutes at ${formatDateTime(new Date(t.datetime),!1)} (Your Time)`,icon:"/favicon.ico"}):alert(`Onyxia buff from ${t.guild} drops in 10 minutes at ${formatDateTime(new Date(t.datetime),!1)} (Your Time)`)):alert(`Onyxia buff from ${t.guild} drops in 10 minutes at ${formatDateTime(new Date(t.datetime),!1)} (Your Time)`)}(o),l.add(d),localStorage.setItem("alertedBuffs",JSON.stringify([...l]))),f<=0){document.getElementById("countdownTimer").textContent="Buff is now!";let u=buffs.filter(e=>{let t=new Date(e.datetime),o=new Date(t.toLocaleString("en-US",{timeZone:n}));return o>i});JSON.stringify(u)!==JSON.stringify(e)&&(buffs=u,displayBuffs(),e=u),localStorage.removeItem("alertedBuffs");return}let m=Math.floor(f/864e5),s=Math.floor(f%864e5/36e5),c=Math.floor(f%36e5/6e4),$=Math.floor(f%6e4/1e3),g;g=0===m?0===s?0===c?`${$}`:`${c}:${$.toString().padStart(2,"0")}`:`${s}:${c.toString().padStart(2,"0")}:${$.toString().padStart(2,"0")}`:`${m}d ${s.toString().padStart(2,"0")}:${c.toString().padStart(2,"0")}:${$.toString().padStart(2,"0")}`,document.getElementById("countdownTimer").textContent=g}t(),setInterval(t,1e3)}loadBuffs(),setInterval(loadBuffs,6e4),displayBuffs();
